- id: default-commit-message
  name: Default commit message for whitespace-only changes
  description: Append "Whitespace-only change" header to proposed commit message.
  entry: default-commit-message
  # args: [--header="Whitespace-only change"]
  language: python
  stages: [prepare-commit-msg]

- id: honest-commit-message
  name: Verify whitespace-only commit message claims are true
  description: If a commit message claims to be changing only whitespace, verify git diff
  entry: honest-commit-message
  # args: [--header="Whitespace-only change"]
  language: python
  stages: [commit-msg]
