- id: default-commit-message
  name: when a whitespace-only commit is being created, default the commit message
  entry: default-commit-message
  language: python
  always_run: true
  stages: [prepare-commit-msg]
  types: [text]

- id: honest-commit-message
  name: when a whitespace-only commit message claim is made, verify only whitespace changes are made
  entry: honest-commit-message
  language: python
  types: [text]